apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloack-external-secret
  namespace: argo
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    path: argocd/applications/keycloak/externalSecret
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
