apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argo
spec:
  project: default
  destination:
    namespace: keycloak
    server: https://kubernetes.default.svc
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 17.2.1
    helm:
      parameters:
      - name: "auth.existingSecret"
        value: keycloak-creds-secret
      - name: "passwordSecretKey"
        value: keycloakPassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

