apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: rancher-issuer
  namespace: cattle-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: rk90229@gmail.com
    privateKeySecretRef:
      name: tls-rancher-ingress
    solvers:
      - http01:
          ingress:
            class: traefik

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rancher-certificate
  namespace: cattle-system
spec:
  secretName: tls-rancher-ingress
  issuerRef:
    name: rancher-issuer 
    kind: Issuer # or "Issuer" if you're using a namespaced issuer
  dnsNames:
    - rancher.rajesh-kumar.in
