apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argo
spec:
  project: default
  destination:
    namespace: prometheus
    name: in-cluster
  source:
    chart: thanos
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.16.1
    helm:
      parameters:
      - name: "receive.enabled"
        value: "true"
      - name: "existingObjstoreSecret"
        value: "thanos-obj-secret"
      - name: "metrics.enabled"
        value: "true"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

