apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos-ingress-route
  namespace: argo
spec:
  project: default
  destination:
    namespace: prometheus
    name: in-cluster
  source:
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    path: argocd/applications/thanos/ingressRoute
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
