apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector
  namespace: argo
spec:
  project: default
  destination:
    namespace: cattle-neuvector-system
    server: https://kubernetes.default.svc
  source:
    chart: core
    repoURL: https://neuvector.github.io/neuvector-helm/
    targetRevision: 2.6.5
    helm:
      parameters:
      - name: "k3s.enabled"
        value: "true"
      - name: "global.cattle.url"
        value: https://rancher.rajesh-kumar.in
      - name: "controller.ranchersso.enabled" 
        value: "true"
      - name: "manager.svc.type"
        value: ClusterIP
      - name: "manager.env.ssl"
        value: "true"
      - name: "controller.apisvc.type"
        value: ClusterIP
      - name: "controller.federation.mastersvc.type"
        value: ClusterIP
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
