apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nv-external-secret
  namespace: argo
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "argocd-alerts"
spec:
  project: default
  destination:
    namespace: cattle-neuvector-system 
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    path: argocd/applications/neuvector/externalSecret
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
