apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    release: loki
spec:
  destination:
    name: in-cluster
    namespace: prometheus
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 5.36.3
    helm:
      values: |-
        fullnameOverride: loki
        ingress:
          enabled: true
          ingressClassName: "traefik"
          hosts:
            - loki.rajesh-kumar.in
          tls:
          - hosts:
            - loki.rajesh-kumar.in
            secretName: rancher-tls-cert 
    chart: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - Replace=true
