apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: loki
spec:
  destination:
    name: practice-cluster
    namespace: prometheus
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 2.9.11
    chart: loki-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
    - Replace=true
