# Example ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  GF_AUTH_GITHUB_ENABLED: "true"
  GF_USERS_ALLOW_SIGN_UP: "false"
  GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
  GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS: "rajesh-personal-account"


