apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neuvector-monitor
  namespace: argo
spec:
  project: default
  destination:
    namespace: cattle-neuvector-system
    name: practice-cluster
  source:
    chart: monitor
    repoURL: https://neuvector.github.io/neuvector-helm/
    targetRevision: 2.6.5
    helm:
      parameters:
      - name: "exporter.grafanaDashboard.enabled"
        value: "true" 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true

