apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvmonitor-external-secret
  namespace: argo
spec:
  project: default
  destination:
    namespace: cattle-neuvector-system 
    name: practice-cluster
  source:
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    path: argocd/applications/neuvector/nv-monitor/externalSecret
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
