apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secret
  namespace: argo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: dex-creds-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: clientID
    remoteRef:
      key: secret/argo/dex
      property: clientID
  - secretKey: clientSecret
    remoteRef:
      key: secret/argo/dex
      property: clientSecret
