apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-secret
  namespace: argo
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: slack-token
    remoteRef:
      key: secret/argo/slack
      property: slack-token
