crds:
  install: true
configs:
  cm:
    url: https://argo-dashboard.rajesh-kumar.in
    dex.config: |
      connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex-creds-secret:clientID
          clientSecret: $dex-creds-secret:clientSecret
          orgs:
          - name: rajesh-personal-account
  rbac:
    create: true
    policy.csv: |
      p, role:devops-role, applications, create, */*, allow
      p, role:devops-role, applications, delete, */*, allow
      p, role:devops-role, applications, get, */*, allow
      p, role:devops-role, applications, override, */*, allow
      p, role:devops-role, applications, sync, */*, allow
      p, role:devops-role, applications, update, */*, allow
      p, role:devops-role, repositories, create, *, allow
      p, role:devops-role, repositories, update, *, allow
      p, role:devops-role, repositories, delete, *, allow
      g, rajesh-personal-account:devops, role:devops-role
    policy.default: role:readonly
    scopes: '[groups]'

redis:
  exporter:
    enabled: true
  metrics:
    enabled: true
server:
  metrics:
    enabled: true
controller:
  metrics:
    enabled: true
notifications:
  logLevel: "debug"
  secret:
    create: false
  metrics:
    enabled: true
  notifiers:
    service.slack: |
      token: $slack-token
  triggers:
    defaultTriggers: |
      - on-deployed
      - on-sync-status-unknown  
    trigger.on-deployed: |
      - description: Application is synced and healthy. Triggered once per commit.
        oncePer: app.status.operationState.syncResult.revision
        send:
        - app-deployed
        when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy' and app.status.sync.status == 'Synced'
  templates:
    template.app-deployed: |
      message: |
        {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} is now running new version of deployments manifests.
      slack:
        attachments: |
          [{
            "title": "{{ .app.metadata.name}}",
            "title_link":"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "color": "#18be52",
            "fields": [
            {
              "title": "Sync Status",
              "value": "{{.app.status.sync.status}}",
              "short": true
            },
            {
              "title": "Repository",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Revision",
              "value": "{{.app.status.sync.revision}}",
              "short": true
            }
            {{range $index, $c := .app.status.conditions}}
            {{if not $index}},{{end}}
            {{if $index}},{{end}}
            {
              "title": "{{$c.type}}",
              "value": "{{$c.message}}",
              "short": true
            }
            {{end}}
            ]
          }]
