apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: prometheus
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: grafana-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: grafanaAdminPass
    remoteRef:
      key: secret/grafana
      property: adminPassword
  - secretKey: grafanaAdminUser
    remoteRef:
      key: secret/grafana
      property: adminUser
  - secretKey: client_id 
    remoteRef:
      key: secret/grafana
      property: githubClientID
  - secretKey: client_secret
    remoteRef:
      key: secret/grafana
      property: githubClientSecret
