apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-node-exporter
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: prometheus-node-exporter
spec:
  destination:
    name: practice-cluster
    namespace: prometheus
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 4.24.0
    helm:
      values: |-
        podAnnotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '9100'
          cluster: 'practice-cluster'
        hostRootFsMount:
          enabled: false
        prometheus:
          monitor:
            enabled: true
    chart: prometheus-node-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
