apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: keycloak
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend-access
    kind: ClusterSecretStore
  target:
    name: keycloak-creds-secret
    creationPolicy: Owner
  data:
  - secretKey: keycloakUser
    remoteRef:
      key: secret/keycloak
      property: keycloakUser
  - secretKey: keycloakPassword
    remoteRef:
      key: secret/keycloak
      property: keycloakPassword
  - secretKey: postgres-password
    remoteRef:
      key: secret/keycloak
      property: pg-admin-pass
  - secretKey: password
    remoteRef:
      key: secret/keycloak
      property: pg-new-user-pass
  - secretKey: preplicationPasswordKey
    remoteRef:
      key: secret/keycloak
      property: pg-replication-pass
  - secretKey: pg-new-user
    remoteRef:
      key: secret/keycloak
      property: pg-new-user
