apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: grafana-operator
spec:
  destination:
    name: practice-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 3.5.8
    helm:
      values: |-
        grafana:
          envFrom:
            - configMapRef:
                name: grafana-config
            - secretRef:
                name: grafana-creds-secret
          config:
            server:
              root_url: "https://grafana.rajesh-kumar.in"
            security:
              admin_user: "{{ .GF_SECURITY_ADMIN_USER }} "
              admin_password: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"

    chart: grafana-operator 
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
