apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: grafana
spec:
  destination:
    name: practice-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 7.0.8
    helm:
      values: |-
        admin:
          existingSecret: "grafana-creds-secret"
          userKey: GF_SECURITY_ADMIN_USER
          passwordKey: GF_SECURITY_ADMIN_PASSWORD
        envFromConfigMaps:
          - name: grafana-config
        envValueFrom:
          GF_AUTH_GITHUB_CLIENT_ID:
            secretKeyRef:
              name: grafana-creds-secret
              key: GF_AUTH_GITHUB_CLIENT_ID
          GF_AUTH_GITHUB_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-creds-secret
              key: GF_AUTH_GITHUB_CLIENT_SECRET
        grafana.ini:
          server:
            root_url: "https://grafana.rajesh-kumar.in"
    chart: grafana
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
