apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-env-cm
  namespace: argo
spec:
  project: default
  destination:
    namespace: monitoring
    name: practice-cluster
  source:
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    path: argocd/applications/grafana/env-cm
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
