apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: personal-setup
  namespace: argo
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-alerts
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-alerts
    notifications.argoproj.io/subscribe.on-deleted.slack: argocd-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argocd-alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argocd-alerts
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argocd-alerts
spec:
  destination:
    namespace: argo
    name: practice-cluster
  project: default
  source:
    path: argocd/applications
    repoURL: https://github.com/rk280392/rancher-k3s-certmanager.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
