apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: kube-prometheus-stack
spec:
  destination:
    name: in-cluster
    namespace: prometheus
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 52.1.0
    helm:
      skipCrds: true
      values: |-
        prometheus:
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                prometheus: argo-cd-grafana
            additionalScrapeConfigs: |
              - job_name: 'argocd'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['argo-argocd-application-controller-metrics.argo.svc.cluster.local:8082', 'argo-argocd-redis-metrics.argo.svc.cluster.local:9121']
              - job_name: 'alertManager'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['alertmanager-operated.prometheus.svc.cluster.local:9093']
              - job_name: 'nodeExporter'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['prometheus-node-exporter.prometheus.svc.cluster.local:9100']
              - job_name: 'kubeMetrics'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['kube-prometheus-stack-kube-state-metrics.prometheus.svc.cluster.local:8080']
              - job_name: 'NeuVector'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['neuvector-prometheus-exporter.cattle-neuvector-system.svc.cluster.local:8068']
              - job_name: 'Keycloak'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['keycloack-keycloak-metrics.keycloak.svc.cluster.local:8080']
        alertmanager:
          enabled: true
        nodeExporter:
          enabled: false
        grafana:
          defaultDashboardsEnabled: false
          defaultDashboardsTimezone: browser
          admin:
            existingSecret: grafana-creds-secret
            userKey: grafanaAdminUser 
            passwordKey: grafanaAdminPass
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - grafana.rajesh-kumar.in
            tls:
              - secretName: rancher-tls-cert 
                hosts:
                  - grafana.rajesh-kumar.in
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
