apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    release: kube-prometheus
spec:
  destination:
    name: practice-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.22.5
    helm:
      values: |-
        clusterDomain: practice-cluster.local
        prometheus:
          externalLabels:
            cluster: "practice-cluster"
          additionalScrapeConfigs:
            enabled: true
            type: internal
            internal:
              jobList:
                - job_name: 'neuvector-practice-cluster'
                  scrape_interval: 30s
                  scrape_timeout: 10s
                  static_configs:
                    - targets: ['neuvector-prometheus-exporter.cattle-neuvector-system.svc.cluster.local:8068']
                      labels:
                        cluster: 'practice-cluster'
          remoteWrite:
            - url: https://thanos.rajesh-kumar.in/api/v1/receive
              basicAuth:
                username:
                  name: grafana-creds-secret
                  key: thanos_receive_user
                password:
                  name: grafana-creds-secret
                  key: thanos_receive_pass
    chart: kube-prometheus
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
